pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo “running CI for master”
            
      - name: scan
        type: XrayScan
        configuration:
          #inherits from bash
          waitUntilFinish:        true  # default true
          inputSteps:
              - name:          step_1          # required
                trigger: false
 
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
